#!/usr/bin/env python3
"""
lab-init — LabOS onboarding and management
Usage:
  python3 lab_init.py                  # full interactive onboarding
  python3 lab_init.py --add-project    # add a new project
  python3 lab_init.py --update-prefs   # update preferences
  python3 lab_init.py --status         # show current lab status
  python3 lab_init.py --reset          # full reset (with confirmation)
  python3 lab_init.py --name "X" --desc "Y"  # non-interactive project add (AI use)
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))
from lab_utils import (
    load_config, save_graph, load_graph,
    award_xp, log_session, progress, section_header,
    checkpoint, confirm, CheckpointAborted,
    upsert_node, now_iso, today_str, LAB_DIR,
    CONFIG_FILE, MEMORY_FILE, GRAPH_FILE, XP_FILE, SESSIONS_DIR,
)

# ── Lab UI state bridge (optional, silent if UI not running) ──────────────────
try:
    sys.path.insert(0, str(Path(__file__).parent.parent / "lab-ui"))
    from lab_state import AgentWorking, working, idle as idle_state, error as error_state
    _UI = True
except ImportError:
    class AgentWorking:
        def __init__(self, *a, **kw): pass
        def __enter__(self): return self
        def update(self, *a): pass
        def __exit__(self, *a): return False
    def working(*a, **kw): pass
    def idle_state(*a): pass
    def error_state(*a): pass
    _UI = False



# ─── Slugify ──────────────────────────────────────────────────────────────────

def slugify(s: str) -> str:
    return re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")


# ─── XP / levels ──────────────────────────────────────────────────────────────

LEVELS = [
    (0,      1,  "Confused First-Year",               "🧪"),
    (300,    2,  "Lab Gremlin",                        "🐾"),
    (800,    3,  "Professional Coffee Drinker",        "☕"),
    (2000,   4,  "PhD Candidate (ABD, technically)",   "📚"),
    (4000,   5,  "Doctor of Suffering",                "🎓"),
    (7500,   6,  "Postdoc (Indentured Servant Edition)","⛓️"),
    (12000,  7,  "Assistant Professor (Broke but Hopeful)","📉"),
    (20000,  8,  "Associate Professor (Tenure Track Anxiety)","😰"),
    (30000,  9,  "Tenured Professor (Finally Relaxed)", "😌"),
    (45000, 10,  "Distinguished Chair of Something Important","🏛️"),
]


def level_from_xp(xp: int) -> tuple:
    result = (1, "Confused First-Year", "🧪")
    for threshold, lvl, title, badge in LEVELS:
        if xp >= threshold:
            result = (lvl, title, badge)
    return result


def init_xp(user: str) -> dict:
    xp_data = {
        "user": user, "xp": 100, "level": 1,
        "level_title": "Confused First-Year",
        "badges": ["🧪 Lab Open"],
        "history": [{"event": "Lab initialized", "xp": 100, "timestamp": now_iso()}],
    }
    XP_FILE.write_text(json.dumps(xp_data, indent=2))
    return xp_data


# ─── File writers ─────────────────────────────────────────────────────────────

def write_config(cfg: dict):
    CONFIG_FILE.parent.mkdir(parents=True, exist_ok=True)
    CONFIG_FILE.write_text(json.dumps(cfg, indent=2))
    print("  ✅ LAB_CONFIG.json")


def write_memory(cfg: dict, project: dict | None = None):
    project_lines = (
        f"- **{project['name']}:** {project['description']} — Status: {project['status']}\n"
        if project else
        "(none yet — add with: `lab-init --add-project`)\n"
    )
    content = f"""# Lab Memory — {cfg['user']}

> Auto-generated by lab-init. Updated after each research session.

## Research Identity
- **Name:** {cfg['user']}
- **Career stage:** {cfg['career_stage']}
- **Primary fields:** {', '.join(cfg['fields'])}
- **Disciplines:** {', '.join(cfg['disciplines'])}

## Tools Connected
- **Knowledge store:** {cfg['knowledge_store']} @ {cfg.get('obsidian_vault') or 'not set'}
- **Notion DB:** {cfg.get('notion_research_db') or 'not connected'}
- **Zotero:** {cfg.get('zotero_type') or 'not connected'}
- **Databases:** {', '.join(cfg['databases'])}

## Preferences
- **Summary style:** {cfg['summary_style']}
- **Papers per batch:** {cfg['papers_per_batch']}
- **Writing voice:** {cfg['writing_style']}
- **Citation format:** {cfg['citation_format']}
- **Feedback intensity:** hard (default)

## Active Projects
{project_lines}
## Interaction Patterns
- Working hours: (to be learned)
- Common blind spots: (to be learned)

## Last Updated
{today_str()} by lab-init
"""
    MEMORY_FILE.parent.mkdir(parents=True, exist_ok=True)
    MEMORY_FILE.write_text(content)
    print("  ✅ LAB_MEMORY.md")


def write_graph(cfg: dict, project: dict | None = None):
    GRAPH_FILE.parent.mkdir(parents=True, exist_ok=True)
    meta = {"type": "Meta", "schema_version": "0.2",
            "created": now_iso(), "owner": cfg["user"]}
    with open(GRAPH_FILE, "w") as f:
        f.write(json.dumps(meta) + "\n")
    if project:
        _append_project_node(project)
    print("  ✅ research-graph.jsonl")


def _append_project_node(project: dict):
    slug   = slugify(project["name"])
    hyps   = [project["hypothesis"]] if project.get("hypothesis") else []
    node   = {
        "type": "Project", "id": f"proj_{slug}",
        "name": project["name"], "description": project["description"],
        "status": project["status"], "hypotheses": hyps,
        "experiments": [], "drafts": [],
        "created": now_iso(), "updated": now_iso(),
    }
    with open(GRAPH_FILE, "a") as f:
        f.write(json.dumps(node) + "\n")


def scaffold_obsidian(vault_path: str, project: dict | None = None) -> bool:
    vault = Path(vault_path)
    if not vault.exists():
        try:
            vault.mkdir(parents=True)
            (vault / ".obsidian").mkdir(exist_ok=True)
            (vault / ".obsidian" / "app.json").write_text("{}")
            print(f"  ✅ New Obsidian vault created at {vault_path}")
        except Exception as e:
            print(f"  ⚠️  Could not create vault: {e}")
            return False

    for folder in ["Research/Projects", "Research/Literature",
                   "Research/Methods", "Research/Weekly-Digests"]:
        (vault / folder).mkdir(parents=True, exist_ok=True)

    (vault / "Research" / "README.md").write_text(
        "# Research Vault\nManaged by LabOS.\n\n"
        "- **Projects/** — notes, hypotheses, drafts per project\n"
        "- **Literature/** — paper summaries from lab-lit-scout\n"
        "- **Methods/** — protocol notes, stats tips\n"
        "- **Weekly-Digests/** — field trend digests\n"
    )

    if project:
        slug     = slugify(project["name"])
        proj_dir = vault / "Research" / "Projects" / slug
        proj_dir.mkdir(parents=True, exist_ok=True)
        (proj_dir / "hypotheses.md").write_text(
            f"# Hypotheses — {project['name']}\n\n"
            + (f"- {project['hypothesis']}\n" if project.get("hypothesis") else "")
        )
        (proj_dir / "notes.md").write_text(
            f"# Notes — {project['name']}\n\n{project.get('description','')}\n"
        )
        (proj_dir / "drafts").mkdir(exist_ok=True)
        print(f"  ✅ Obsidian project folder: Research/Projects/{slug}/")

    print(f"  ✅ Obsidian vault scaffolded")
    return True


def register_cron(cfg: dict):
    day_map = {"Monday": 1, "Tuesday": 2, "Wednesday": 3, "Thursday": 4,
               "Friday": 5, "Saturday": 6, "Sunday": 0}
    day_num  = day_map.get(cfg.get("weekly_trend_day", "Monday"), 1)
    h, m     = cfg.get("weekly_trend_time", "08:00").split(":")
    schedule = f"{m} {h} * * {day_num}"
    try:
        result = subprocess.run(
            ["openclaw", "cron", "add",
             "--name", "lab-field-trend-weekly",
             "--schedule", schedule,
             "--skill", "lab-field-trend",
             "--args", "--no-interactive"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0:
            print(f"  ✅ Weekly trend cron: {cfg['weekly_trend_day']}s at {cfg['weekly_trend_time']}")
        else:
            raise Exception(result.stderr.strip())
    except Exception as e:
        print(f"  ⚠️  Cron registration failed: {e}")
        print(f"     Add manually: openclaw cron add --name lab-field-trend-weekly --schedule '{schedule}' --skill lab-field-trend")


# ─── Collection helpers ───────────────────────────────────────────────────────

def ask_list(question: str, default: str = "") -> list[str]:
    """checkpoint() returning a comma-split list."""
    try:
        raw = checkpoint(question, default=default, emoji="📋")
    except CheckpointAborted:
        raw = default
    return [x.strip() for x in raw.split(",") if x.strip()]


def collect_identity() -> dict:
    section_header("── Identity")
    try:
        name = checkpoint("Your name (for personalization)", default="Researcher", emoji="👤")
    except CheckpointAborted:
        name = "Researcher"
    try:
        stage = checkpoint(
            "Career stage?",
            options=["undergrad", "masters", "phd", "postdoc", "faculty", "independent"],
            default="postdoc", allow_freetext=False, emoji="🎓",
        )
    except CheckpointAborted:
        stage = "postdoc"
    fields      = ask_list("Primary research field(s) (comma-separated)", "neuroscience, machine learning")
    disciplines = ask_list("Disciplines spanned", "biomedical, computational")
    return {"user": name, "career_stage": stage, "fields": fields, "disciplines": disciplines}


def collect_tools() -> dict:
    section_header("── Knowledge Store & Tools")

    obsidian = None
    notion_db = None

    try:
        store = checkpoint(
            "Knowledge store?",
            options=["obsidian", "notion", "none"],
            default="obsidian", allow_freetext=False, emoji="📂",
        )
    except CheckpointAborted:
        store = "obsidian"

    if store == "obsidian":
        try:
            action = checkpoint(
                "Obsidian: create new vault or use existing?",
                options=["new", "existing"],
                default="new", allow_freetext=False, emoji="📁",
            )
        except CheckpointAborted:
            action = "existing"
        default_path = str(Path.home() / "LabOS-Vault")
        try:
            obsidian = checkpoint(
                "Vault path?",
                default=default_path, emoji="📁",
            )
        except CheckpointAborted:
            obsidian = default_path

    elif store == "notion":
        print("  → Go to notion.so → create a 'Papers' database → copy the database ID")
        try:
            notion_db = checkpoint("Notion database ID (or Enter to skip)", default="", emoji="📝")
        except CheckpointAborted:
            notion_db = ""
        notion_db = notion_db or None

    # Zotero
    zotero_type = None
    zotero_lib  = None
    try:
        use_zotero = confirm("Do you use Zotero?", default=False)
    except CheckpointAborted:
        use_zotero = False
    if use_zotero:
        try:
            zotero_type = checkpoint("Zotero type?", options=["local", "web"],
                                     default="web", allow_freetext=False, emoji="📚")
        except CheckpointAborted:
            zotero_type = "web"
        if zotero_type == "web":
            try:
                zotero_lib = checkpoint("Zotero library ID?", default="", emoji="📚") or None
            except CheckpointAborted:
                zotero_lib = None

    # Databases
    db_raw = ask_list(
        "Literature databases (pubmed, openalex, arxiv, semanticscholar, biorxiv)",
        "pubmed, openalex, arxiv"
    )
    valid  = {"pubmed", "openalex", "arxiv", "semanticscholar", "biorxiv"}
    dbs    = [d.lower() for d in db_raw if d.lower() in valid] or ["pubmed", "openalex", "arxiv"]

    return {
        "knowledge_store":    store,
        "obsidian_vault":     obsidian,
        "notion_research_db": notion_db,
        "zotero_type":        zotero_type,
        "zotero_library_id":  zotero_lib,
        "databases":          dbs,
    }


def collect_prefs() -> dict:
    section_header("── Preferences")
    try:
        writing_style = checkpoint(
            "Writing style preference?",
            default="concise, methods-forward, active voice", emoji="✍️",
        )
    except CheckpointAborted:
        writing_style = "concise, methods-forward, active voice"
    try:
        citation = checkpoint(
            "Citation format?",
            options=["APA", "Vancouver", "Nature", "Chicago", "MLA"],
            default="APA", allow_freetext=False, emoji="📚",
        )
    except CheckpointAborted:
        citation = "APA"
    try:
        summary = checkpoint(
            "Paper summary style?",
            options=["bullet", "paragraph", "detailed"],
            default="bullet", allow_freetext=False, emoji="📋",
        )
    except CheckpointAborted:
        summary = "bullet"
    try:
        batch_raw = checkpoint("Papers per batch to review?", default="5", emoji="📄")
        batch = int(batch_raw)
    except (CheckpointAborted, ValueError):
        batch = 5

    return {
        "writing_style":   writing_style,
        "citation_format": citation,
        "summary_style":   summary,
        "papers_per_batch": batch,
    }


def collect_notifications() -> dict:
    section_header("── Notifications")
    try:
        channel = checkpoint(
            "Weekly digest channel?",
            options=["discord", "slack", "none"],
            default="discord", allow_freetext=False, emoji="🔔",
        )
    except CheckpointAborted:
        channel = "discord"
    try:
        trend_day = checkpoint(
            "Weekly trend day?",
            options=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"],
            default="Monday", allow_freetext=False, emoji="📅",
        )
    except CheckpointAborted:
        trend_day = "Monday"
    try:
        trend_time = checkpoint("Delivery time (HH:MM)?", default="08:00", emoji="⏰")
    except CheckpointAborted:
        trend_time = "08:00"
    return {"notify_channel": channel, "weekly_trend_day": trend_day, "weekly_trend_time": trend_time}


def collect_project() -> dict | None:
    section_header("── First Project (optional)")
    try:
        go = confirm("Set up your first research project now?", default=True)
    except CheckpointAborted:
        go = False
    if not go:
        return None
    try:
        name = checkpoint("Project name?", default="My Research Project", emoji="📁")
        desc = checkpoint("One-line description?", emoji="📝")
        hyp  = checkpoint("Main hypothesis? (Enter to skip)", default="", emoji="💡")
        status = checkpoint(
            "Current status?",
            options=["idea", "active", "writing", "submitted", "published"],
            default="active", allow_freetext=False, emoji="📊",
        )
    except CheckpointAborted:
        return None
    return {"name": name, "description": desc, "hypothesis": hyp, "status": status}


# ─── Commands ─────────────────────────────────────────────────────────────────

def cmd_init():
    # Already initialised?
    if CONFIG_FILE.exists():
        try:
            existing = json.loads(CONFIG_FILE.read_text())
        except Exception:
            existing = None
        if existing:
            print(f"\n🧪 LabOS already set up for {existing.get('user','?')}.")
            try:
                action = checkpoint(
                    "What do you want to do?",
                    options=["add-project", "update-prefs", "status", "reset"],
                    default="add-project", allow_freetext=False, emoji="🔀",
                )
            except CheckpointAborted:
                return
            if action == "add-project":
                cmd_add_project()
            elif action == "update-prefs":
                cmd_update_prefs()
            elif action == "status":
                cmd_status()
            elif action == "reset":
                cmd_reset()
            return

    print("\n🧪 Welcome to LabOS — setting up your virtual research lab.\n")

    identity      = collect_identity()
    tools         = collect_tools()
    prefs         = collect_prefs()
    notifications = collect_notifications()
    project       = collect_project()

    cfg = {
        **identity, **tools, **prefs, **notifications,
        "labos_version": "0.2",
        "created": now_iso(),
    }

    section_header("── Creating files")
    SESSIONS_DIR.mkdir(parents=True, exist_ok=True)
    write_config(cfg)
    write_memory(cfg, project)
    write_graph(cfg, project)
    xp_data = init_xp(cfg["user"])
    print(f"  ✅ xp.json  (Level 1 — Confused First-Year 🧪, 100 XP)")

    # Obsidian scaffold
    obsidian_ok = False
    if cfg.get("obsidian_vault"):
        obsidian_ok = scaffold_obsidian(cfg["obsidian_vault"], project)

    # Security baseline — run lab-security audit silently
    progress("Running security baseline…", "🔒")
    try:
        subprocess.run(
            [sys.executable,
             str(Path(__file__).parent / "lab-security" / "lab_security.py"),
             "--mode", "audit"],
            capture_output=True, timeout=15
        )
        print("  ✅ Security baseline complete")
    except Exception:
        print("  ⚠️  lab-security not available — run manually: lab-security --mode audit")

    # Cron
    if cfg["notify_channel"] != "none":
        register_cron(cfg)

    # Summary
    print("\n" + "═"*60)
    print(f"  ✅ LabOS initialized — {cfg['user']}")
    print("═"*60)
    print(f"\n👤 {cfg['user']} ({cfg['career_stage']})")
    print(f"🔬 Fields: {', '.join(cfg['fields'])}")
    print(f"📚 Vault: {cfg.get('obsidian_vault') or 'not set'}")
    print(f"📊 Databases: {', '.join(cfg['databases'])}")
    if project:
        print(f"📁 First project: {project['name']}")
    print(f"\n🏆 XP: 100 | Level 1 — Confused First-Year 🧪")
    print(f"📅 Weekly digest: {cfg['weekly_trend_day']}s at {cfg['weekly_trend_time']} → {cfg['notify_channel']}")
    print(f"\n💡 Try:\n"
          f"   'What's new in my field this week?'   → lab-field-trend\n"
          f"   'Find papers on [your topic]'          → lab-lit-scout\n"
          f"   'Advise me on my project'              → lab-research-advisor")

    log_session("lab-init", cfg["user"], f"Lab initialized. Project: {project['name'] if project else 'none'}")


def cmd_add_project(project: dict | None = None):
    if not CONFIG_FILE.exists():
        print("❌ No LAB_CONFIG.json. Run lab-init first.")
        sys.exit(1)
    cfg = json.loads(CONFIG_FILE.read_text())

    if project is None:
        section_header("── Add New Project")
        project = collect_project()
        if not project:
            print("Cancelled.")
            return

    _append_project_node(project)
    print(f"  ✅ Added to research-graph.jsonl")

    # Update LAB_MEMORY
    if MEMORY_FILE.exists():
        mem = MEMORY_FILE.read_text()
        entry = f"- **{project['name']}:** {project['description']} — Status: {project['status']}\n"
        mem = mem.replace(
            "(none yet — add with: `lab-init --add-project`)\n", ""
        ).replace("## Active Projects\n", f"## Active Projects\n{entry}")
        MEMORY_FILE.write_text(mem)
        print("  ✅ LAB_MEMORY.md updated")

    # Obsidian folder
    if cfg.get("obsidian_vault"):
        vault = Path(cfg["obsidian_vault"])
        if vault.exists():
            slug     = slugify(project["name"])
            proj_dir = vault / "Research" / "Projects" / slug
            proj_dir.mkdir(parents=True, exist_ok=True)
            (proj_dir / "hypotheses.md").write_text(
                f"# Hypotheses — {project['name']}\n\n"
                + (f"- {project['hypothesis']}\n" if project.get("hypothesis") else "")
            )
            (proj_dir / "notes.md").write_text(f"# Notes — {project['name']}\n\n{project['description']}\n")
            (proj_dir / "drafts").mkdir(exist_ok=True)
            print(f"  ✅ Obsidian: Research/Projects/{slug}/")

    award_xp(50, None)
    print(f"\n✅ Project '{project['name']}' added! +50 XP 🎉")


def cmd_update_prefs():
    if not CONFIG_FILE.exists():
        print("❌ No LAB_CONFIG.json. Run lab-init first.")
        sys.exit(1)
    cfg  = json.loads(CONFIG_FILE.read_text())
    prefs = collect_prefs()
    notif = collect_notifications()
    cfg.update({**prefs, **notif})
    CONFIG_FILE.write_text(json.dumps(cfg, indent=2))
    print("\n✅ Preferences updated.")


def cmd_status():
    if not CONFIG_FILE.exists():
        print("❌ No lab found. Run lab-init to get started.")
        sys.exit(1)
    cfg = json.loads(CONFIG_FILE.read_text())
    xp_data = {}
    if XP_FILE.exists():
        xp_data = json.loads(XP_FILE.read_text())

    xp      = xp_data.get("xp", 0)
    level   = xp_data.get("level", 1)
    title   = xp_data.get("level_title", "Confused First-Year")
    badges  = " ".join(xp_data.get("badges", []))

    # Count projects from graph
    n_projects = 0
    n_papers   = 0
    if GRAPH_FILE.exists():
        for line in GRAPH_FILE.read_text().splitlines():
            try:
                rec = json.loads(line)
                if rec.get("type") == "Project": n_projects += 1
                if rec.get("type") == "Paper":   n_papers   += 1
            except Exception:
                pass

    section_header("🔬 LabOS Status")
    print(f"\n👤 {cfg['user']} ({cfg['career_stage']})")
    print(f"🔬 {', '.join(cfg['fields'])}")
    print(f"🏆 Level {level} — {title} | XP: {xp}")
    if badges:
        print(f"🏅 {badges}")
    print(f"\n📁 Projects: {n_projects}  |  📄 Papers: {n_papers}")
    print(f"📚 Vault: {cfg.get('obsidian_vault') or 'not set'}")
    print(f"📊 Databases: {', '.join(cfg['databases'])}")
    print(f"📅 Weekly digest: {cfg['weekly_trend_day']}s at {cfg['weekly_trend_time']} → {cfg['notify_channel']}")
    print(f"\n📄 Config:  {CONFIG_FILE}")
    print(f"🧠 Memory:  {MEMORY_FILE}")
    print(f"🗂️  Graph:   {GRAPH_FILE}")


def cmd_reset():
    print("⚠️  This will delete ALL LabOS data (config, memory, projects, XP).")
    try:
        go = confirm("Are you sure?", default=False)
    except CheckpointAborted:
        go = False
    if not go:
        print("Cancelled.")
        return
    for f in [CONFIG_FILE, MEMORY_FILE, GRAPH_FILE, XP_FILE]:
        if f.exists():
            f.unlink()
            print(f"  ✗ Deleted {f.name}")
    print("\nLab reset. Run lab-init to start fresh.")


# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="LabOS — virtual research lab setup")
    parser.add_argument("--add-project",  action="store_true")
    parser.add_argument("--update-prefs", action="store_true")
    parser.add_argument("--status",       action="store_true")
    parser.add_argument("--reset",        action="store_true")
    # Non-interactive project creation (used by AI agents)
    parser.add_argument("--name",        help="Project name")
    parser.add_argument("--desc",        help="Project description")
    parser.add_argument("--hypothesis",  default="")
    parser.add_argument("--proj-status", default="active",
                        choices=["idea","active","writing","submitted","published"])
    args = parser.parse_args()

    # Non-interactive AI-mediated project add
    if args.name and args.desc:
        cmd_add_project({
            "name": args.name, "description": args.desc,
            "hypothesis": args.hypothesis, "status": args.proj_status,
        })
    elif args.add_project:
        cmd_add_project()
    elif args.update_prefs:
        cmd_update_prefs()
    elif args.status:
        cmd_status()
    elif args.reset:
        cmd_reset()
    else:
        cmd_init()


if __name__ == "__main__":
    with AgentWorking("main", "Initializing lab..."):
        main()
